from typing import Any, Optional
from fastapi import HTTPException, status


class CustomException(HTTPException):
    def __init__(
        self,
        status_code: Optional[int] = None ,
        detail: Any = None,
        headers: Optional[dict[str, str]] = None,
    ) -> None:
        if not status_code :
            status_code=status.HTTP_401_UNAUTHORIZED

        super().__init__(status_code=status_code, detail=detail, headers=headers)

    def __repr__(self) -> str:
        return {"data" : {}, "is_success" : "false", "error" : f"(status_code={self.status_code!r}, detail={self.detail})"}
    

class Exceptions:
    REQUEST_LIMIT_EXHAUSTED= "REQUEST_LIMIT_EXHAUSTED"
    USER_NOT_FOUND="USER_NOT_FOUND. CHECK_CREDENTIALS"
    INCORRECT_EMAIL_PASSWORD="INCORRECT_EMAIL_PASSWORD"
    ACCOUNT_CREATION_FAILED="ACCOUNT_CREATION_FAILED"
    EMAIL_HAS_BEEN_REGISTERED="EMAIL_HAS_BEEN_REGISTERED"
    USERNAME_HAS_BEEN_TAKEN="USERNAME_HAS_BEEN_TAKEN"
    PHONE_NUMBER_HAS_BEEN_REGISTERED="PHONE_NUMBER_HAS_BEEN_REGISTERED"
    CREDENTIAL_ERROR_EXCEPTION="CREDENTIAL_ERROR_EXCEPTION"
    INVALID_API="INVALID_API"
    WRONG_IP="WRONG_IP"
    WRONG_PASSWORD="WRONG_PASSWORD"
    
    SERVICE_NOT_AVAILABLE="THIS SERVICE NOT AVAILABLE"
    SERVICE_NOT_VERIFIED =" YOUR SERVICE REQUEST IS NOT VERIFIED YET, YOU CAN NOT MAKE ANY ACTION NOW "
    USER_NOT_VERIFIED =" YOUR ACCOUNT IS NOT VERIFIED YET , KINDLY CONTACT ORG ADMIN. YOU CAN NOT MAKE ANY ACTION NOW "
    NOT_AUTHORIZED =" YOU ARE NOT AUTHORIZED TO DO THIS ACTION "
    API_KEY_UNAVAILABLE =" ADD RIGHT API_KEY IN THE HEADER "
    TRYING_FROM_DIFFERENT_DEVICE =" YOU ARE TRYING FROM DIFFERENT DEVICE, TRY LOGIN AGAIN "
    FAILED_TO_VALIDATE_CREDENTIALS =" FAILED TO VALIDATE TOKEN CREDENTIALS, LOGIN AGAIN "
    OPERATION_FAILED =" OPERAION FAILED "
    USER_HAS_BEEN_DELETED =" USER HAS BEEN DELETED, CONTACT SERVICE ADMIN TO REACTIVE "
    ACCESS_TOKEN_EXPIRED =" TRY LOGIN AGAIN, ACCESS TOKEN HAS BEEN EXPIRED "
    ACCESS_TOKEN_NOT_VALID =" TRY LOGIN AGAIN, ACCESS TOKEN IS NO LONGER VALID "
    ORDER_ALREADY_BOUGHT =" YOU HAVE BOUGHT THIS ORDER RIGHT NOW. SAME ORDER CAN NOT BE BOUGHT ON THE SPAN OF 30 MINTS "
    FAILED_TO_CREATE_NEW_ORDER =" FAILED TO CREATE ORDER "
    UNAVAILABLE_ORDER_STATUS =" UNAVAILABLE ORDER STATUS "
    NO_UPDATE_FOR_TEST_ORG_RULE="I understand your enthusiasm, But as You cant do this action being under TEST_ORG. I encourage you to create a new service and contact super admin to get verified and then test the complete features of EBASE, For more follow thi link : "