class RedisConstant:
    PREFIX="CRUX_"
    
    TOKEN="TOKEN_"
    TTL="TTL_"
    USER_ORDERS="USER_ORDERS_"
    ORDER_OBJ="ORDER_OBJ_"
    USER_OBJECT="USER_OBJECT_"
    USER_ACCESS_TOKEN="USER_ACCESS_TOKEN_"

    # Api cache
    SERVICE_API="SERVICE_API_"
    SERVICE_ORG="SERVICE_ORG_"
    DAILY_REQUEST_LEFT="DAILY_REQUEST_LEFT_"
    IP_PORTS_SET="IP_PORTS_SET_"
    IS_SERVICE_VERIFIED="IS_SERVICE_VERIFIED_"