class RedisConstant:
    PREFIX="CRUX_"
    
    TOKEN="TOKEN_"
    TTL="TTL_"
    USER_ORDERS_SET="USER_ORDERS_SET"
    ORDER_OBJ="ORDER_OBJ_"
    USER_OBJECT="USER_OBJECT_"
    USER_PRODUCT_SET="USER_PRODUCT_SET_"
    USER_OTP="USER_OTP_"
    USER_EMAIL_MAP="USER_EMAIL_MAP_"

    # Api cache
    SERVICE_API="SERVICE_API_"
    SERVICE_ORG="SERVICE_ORG_"
    DAILY_REQUEST_LEFT="DAILY_REQUEST_LEFT_"
    IP_PORTS_SET="IP_PORTS_SET_"
    IS_SERVICE_VERIFIED="IS_SERVICE_VERIFIED_"