class RedisConstant:
    PREFIX="CRUX_"
    
    TOKEN="TOKEN_"
    TTL="TTL_"
    USER_ORDERS="USER_ORDERS_"
    ORDER_OBJ="ORDER_OBJ_"

    # Api cache
    SERVICE_API="SERVICE_API_"
    SERVICE_ORG="SERVICE_ORG_"
    DAILY_REQUEST_LEFT="_DAILY_REQUEST_LEFT"
    IP_PORTS_SET="IP_PORTS_SET_"
    IS_SERVICE_VERIFIED="IS_SERVICE_VERIFIED_"